name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger action on push to 'main' branch (or your default branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # You can change this to match the version used by your Docusaurus project

      - name: Install dependencies
        run: |
          npm install

      - name: Build Docusaurus site
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # The directory containing your Docusaurus site build
          publish_branch: gh-pages  # The branch to deploy to (gh-pages)
